import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/layout";

export default function Home() {
  const socmed = [
    { src: "/telegram.png", href: "https://t.me/Kamilmuhammad12" },
    { src: "/github.png", href: "https://github.com/Kamilmuhammad" },
    {
      src: "/instagram.png",
      href: "https://www.instagram.com/kamilmuhammad12/",
    },
    { src: "/linkedin.png", href: "www.linkedin.com/in/kamilmuhammad12" },
  ];
  return (
    <>
      <Head>
        <title>Kamil Muhammad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Layout>
        <section>
          <header className="lg:grid-cols-3 lg:grid text-zinc-600 ">
            <div className="lg:order-1 ">
              <Image
                src={"/fotokamil.jpeg"}
                width={200}
                height={200}
                alt={"header Img"}
                className="w-8/12 lg:w-full rounded-3xl mx-auto lg:mb-0 mb-10"
              />
            </div>
            <div className="col-span-2 flex flex-col justify-around lg:gap-0 gap-5 text-center lg:text-left">
              <h1 className="text-4xl lg:text-7xl font-extrabold">
                Kamil <br className="hidden lg:block" /> Muhammad
              </h1>
              <h2 className="robot text-2xl  font-extrabold italic">
                Web Developer
              </h2>
              <p>
                I am a junior Front End Web Developer who wants to learn to
                develop web.
              </p>
              <div className="flex items-center gap-3 mb-2 justify-center lg:justify-start">
                {socmed.map((item) => (
                  <a
                    key={item.src}
                    href={item.href}
                    target="_blank"
                    className="hover:animate-spin"
                  >
                    <Image
                      src={item.src}
                      alt={item.src}
                      width={20}
                      height={20}
                    />
                  </a>
                ))}
              </div>
              <div>
                <a
                  href="mailto:kamil120201@gmail.com"
                  className="bg-gradient-to-l from-slate-600 to-slate-900 text-white py-3 px-2 rounded-lg shadow-2xl shadow-slate-800 hover:from-slate-900 hover:to-slate-800 duration-1000"
                >
                  Connect with me
                </a>
              </div>
            </div>
          </header>
        </section>
      </Layout>
    </>
  );
}
